Algoritmo "ApiBd1°Sem"

Var
//limite maximo de médicos:
Max_Med : inteiro
//quantidade total de médicos do hospital
total_med : inteiro
//quantidade de médicos por plantão
med_plant : inteiro
//quantidade de clinico geral manhã
qtd_CGm : inteiro
//quantidad de cirurgião de manhã
qtd_Cm  : inteiro
//quatidade de pediatra de  manhã
qtd_PEDm : inteiro
//quantidade de clinico geral de tarde
qtd_CGt  : inteiro
//quatidade de  cirurgião de tarde
qtd_Ct : inteiro
//quantidade de pediatra de tarde
qtd_PEDt : inteiro
//quatidade de clinico geral de noite
qtd_CGn : inteiro
//quantidade de cirutgião de noite
qtd_Cn : inteiro
//quandtidade de pediatra de noite
qtd_PEDn : inteiro
//quantidade minima de médicos
min_med : inteiro
//quantidade minima de clinicos gerais
min_CG : inteiro
//quantidade minima de cirurgião
min_C : inteiro
//quantidade minima de pediatra
min_PED : inteiro

Inicio
//esse é o valor que o maior complexo hospitalar do Brasil suporta referente
// a profissionais da saude
Max_Med <- 1400
//quantidade minima de cada especialidade e de médicos
min_med <- 4
//minimo de clinicos gerais
min_CG <- 2
//minimo de cirurgião
min_C <- 1
//minimo de pediatra
min_PED <- 1

Fimalgoritmo